### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by fengyanWang** [OpenMOSS/MOSS-TTSD#22]
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')

按照指示安装了相关库，但是运行python inference.py --jsonl examples/examples.jsonl --output_dir outputs --seed 42 --use_normalize命令时报错如上

**Comment by CloudRipple** [comment]
这个信息在我们运行的时候也会出现，是正常的提示信息。如果程序无法正常运行，请提供除此之外的报错信息，以便我们分析

**Comment by fengyanWang** [comment]
> 这个信息在我们运行的时候也会出现，是正常的提示信息。如果程序无法正常运行，请提供除此之外的报错信息，以便我们分析

RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by CloudRipple** [comment]
尝试运行以下指令，并提供它的报错信息
```bash
CUDA_LAUNCH_BLOCKING=1 python inference.py --jsonl examples/examples.jsonl --output_dir outputs --seed 42 --use_normalize
```
并请提供一下完整的环境信息，包括显卡信息，驱动版本，CUDA版本等

**Comment by fengyanWang** [comment]
> CUDA_LAUNCH_BLOCKING=1

还是报同样的错误，报错信息如下：
Using device: cuda
Using dtype: bf16 (torch.bfloat16)
Using attention implementation: flash_attention_2
Loading models...
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Loaded 2 items from examples/examples.jsonl
Set random seed to 42
Starting inference...
Processing 2 samples starting from index 0...
Using speaker1 and speaker2 information for prompt audio and text.
Using speaker1 and speaker2 information for prompt audio and text.
Starting batch audio generation...
Error during batch processing: CUDA error: device kernel image is invalid
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/inference.py", line 104, in <module>
    main()
  File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/inference.py", line 75, in main
    actual_texts_data, audio_results = process_batch(
  File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/generation_utils.py", line 397, in process_batch
    outputs = model.generate(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/generation/utils.py", line 2625, in generate
    result = self._sample(
  File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/modeling_asteroid.py", line 115, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/modeling_asteroid.py", line 356, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/modeling_asteroid.py", line 272, in forward
    outputs = self.language_model(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/utils/generic.py", line 943, in wrapper
    output = func(self, *args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 458, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/modeling_layers.py", line 83, in __call__
    return super().__call__(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 262, in forward
    hidden_states, self_attn_weights = self.self_attn(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 217, in forward
    attn_output, attn_weights = attention_interface(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/integrations/flash_attention.py", line 65, in flash_attention_forward
    attn_output = _flash_attention_forward(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 530, in _flash_attention_forward
    attn_output_unpad = _flash_attn_varlen_func(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 1443, in flash_attn_varlen_func
    return FlashAttnVarlenFunc.apply(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 925, in forward
    out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_varlen_forward(
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_ops.py", line 1158, in __call__
    return self._op(*args, **(kwargs or {}))
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/autograd.py", line 113, in autograd_impl
    result = forward_no_grad(*args, Metadata(keyset, keyword_only_args))
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/autograd.py", line 40, in forward_no_grad
    result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_ops.py", line 761, in redispatch
    return self._handle.redispatch_boxed(keyset, *args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 335, in backend_impl
    result = self._backend_fns[device_type](*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_compile.py", line 51, in inner
    return disable_fn(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 367, in wrapped_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 165, in _flash_attn_varlen_forward
    out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(
RuntimeError: CUDA error: device kernel image is invalid
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by fengyanWang** [comment]
> > CUDA_LAUNCH_BLOCKING=1
> 
> 还是报同样的错误，报错信息如下： Using device: cuda Using dtype: bf16 (torch.bfloat16) Using attention implementation: flash_attention_2 Loading models... You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`. /root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`. WeightNorm.apply(module, name, dim) Loaded 2 items from examples/examples.jsonl Set random seed to 42 Starting inference... Processing 2 samples starting from index 0... Using speaker1 and speaker2 information for prompt audio and text. Using speaker1 and speaker2 information for prompt audio and text. Starting batch audio generation... Error during batch processing: CUDA error: device kernel image is invalid Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> Traceback (most recent call last): File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/inference.py", line 104, in main() File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/inference.py", line 75, in main actual_texts_data, audio_results = process_batch( File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/generation_utils.py", line 397, in process_batch outputs = model.generate( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/generation/utils.py", line 2625, in generate result = self._sample( File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/modeling_asteroid.py", line 115, in _sample outputs = self(**model_inputs, return_dict=True) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl return forward_call(*args, **kwargs) File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/modeling_asteroid.py", line 356, in forward outputs = self.model( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl return forward_call(*args, **kwargs) File "/ai-train/wfy_pro/temp_pro/MOSS-TTSD/modeling_asteroid.py", line 272, in forward outputs = self.language_model( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl return forward_call(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/utils/generic.py", line 943, in wrapper output = func(self, *args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 458, in forward layer_outputs = decoder_layer( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/modeling_layers.py", line 83, in **call** return super().**call**(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl return forward_call(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 262, in forward hidden_states, self_attn_weights = self.self_attn( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl return forward_call(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/models/qwen3/modeling_qwen3.py", line 217, in forward attn_output, attn_weights = attention_interface( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/integrations/flash_attention.py", line 65, in flash_attention_forward attn_output = _flash_attention_forward( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 530, in _flash_attention_forward attn_output_unpad = _flash_attn_varlen_func( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 1443, in flash_attn_varlen_func return FlashAttnVarlenFunc.apply( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 925, in forward out_padded, softmax_lse, S_dmask, rng_state = _wrapped_flash_attn_varlen_forward( File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_ops.py", line 1158, in **call** return self._op(*args, **(kwargs or {})) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/autograd.py", line 113, in autograd_impl result = forward_no_grad(*args, Metadata(keyset, keyword_only_args)) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/autograd.py", line 40, in forward_no_grad result = op.redispatch(keyset & _C._after_autograd_keyset, *args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_ops.py", line 761, in redispatch return self._handle.redispatch_boxed(keyset, *args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 335, in backend_impl result = self._backend_fns[device_type](*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_compile.py", line 51, in inner return disable_fn(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn return fn(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/torch/_library/custom_ops.py", line 367, in wrapped_fn return fn(*args, **kwargs) File "/root/miniconda3/envs/moss_ttsd/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 165, in _flash_attn_varlen_forward out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd( RuntimeError: CUDA error: device kernel image is invalid Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.



> 尝试运行以下指令，并提供它的报错信息
> 
> CUDA_LAUNCH_BLOCKING=1 python inference.py --jsonl examples/examples.jsonl --output_dir outputs --seed 42 --use_normalize
> 并请提供一下完整的环境信息，包括显卡信息，驱动版本，CUDA版本等

显卡信息：NVIDIA GeForce RTX 4090
驱动版本：Driver Version: 535.86.10
CUDA Version: 12.2
torch：2.7.1
transformers：4.53.2

**Comment by cms42** [comment]
> 请问您的 flash attention 版本是 2.8.1 吗

@fengyanWang 

我们已经确定，由于打包配置修改([8ba246f](https://github.com/Dao-AILab/flash-attention/commit/8ba246f6cc8813d41f9289e2781b7d8fa22a97cb))，`flash attention 2.8.1`需要 **550或更高** 的Driver版本

（详情请参见NVCC文档[对compress-mode compatibility的说明](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#compress-mode-default-size-speed-balance-none-compress-mode)；另见相关[issue](https://github.com/Dao-AILab/flash-attention/issues/1750)和[pr](https://github.com/Dao-AILab/flash-attention/pull/1751) ）

我们建议您
- 将`flash attention`暂时降级到2.8.0，这是推荐的方案

或者，您也可以考虑
- 修改`flash attention`的`setup.py`，禁用`device code compression`并自行编译安装，这需要更多的工作量

当然如果可能，推荐您 **始终使用最新稳定版Nvidia Driver**

**Comment by fengyanWang** [comment]
> > 请问您的 flash attention 版本是 2.8.1 吗
> 
> [@fengyanWang](https://github.com/fengyanWang)
> 
> 我们已经确定，由于打包配置修改([8ba246f](https://github.com/Dao-AILab/flash-attention/commit/8ba246f6cc8813d41f9289e2781b7d8fa22a97cb))，`flash attention 2.8.1`需要 **550或更高** 的Driver版本
> 
> （详情请参见NVCC文档[对compress-mode compatibility的说明](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#compress-mode-default-size-speed-balance-none-compress-mode)；另见相关[issue](https://github.com/Dao-AILab/flash-attention/issues/1750)和[pr](https://github.com/Dao-AILab/flash-attention/pull/1751) ）
> 
> 我们建议您
> 
> * 将`flash attention`暂时降级到2.8.0，这是推荐的方案
> 
> 或者，您也可以考虑
> 
> * 修改`flash attention`的`setup.py`，禁用`device code compression`并自行编译安装，这需要更多的工作量
> 
> 当然如果可能，推荐您 **始终使用最新稳定版Nvidia Driver**

感谢，问题已经解决
